database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: Anilkumar@1423
  database: amazon_clone_backend
  


port: 3000

email:
  SERVICE: 'Gmail'
  HOST: 'smtp.gmail.com'
  PORT: 587
  SECURE: false
  EMAIL_USER: anil.craftnotion@gmail.com
  EMAIL_PASSWORD: "tbdbqtoxkrntsvsn"
  BASE_URL: http://localhost:3000
  FROM_NAME: 'Amazon Clone'
  TLS_REJECT_UNAUTHORIZED: false 

secretKey:
  secret: ANIL.@1423-ANIL.@1423-ANIL.@1423
